name: Bug report
description: Report a reproducible issue in AIForDriver modules.
labels: [bug]
body:
  - type: input
    id: module
    attributes:
      label: Affected module
  - type: textarea
    id: description
    attributes:
      label: Description
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
